before:
  hooks:
    - go mod download
    - golint ./...
builds:
  -
    main: cmd/ping_exporter/main.go
    env:
      - CGO_ENABLED=0
    goos: 
      - linux
    goarch: 
      - arm
    goarm: 
      - "7"
      
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
